### ISSUE TITLE
PDF bot error uploaded pdf file but cannot chat due to below error

### ISSUE THREAD

**Issue by syedazharmbnr1** [docker/genai-stack#108]
pdf_bot-1     | 2024-01-04 06:36:05.583 Embedding: Using SentenceTransformer
pdf_bot-1     | 2024-01-04 06:36:05.583 LLM: Using Ollama: llama2
api-1         | INFO:     127.0.0.1:44452 - "GET / HTTP/1.1" 200 OK
api-1         | INFO:     127.0.0.1:44454 - "GET / HTTP/1.1" 200 OK
api-1         | INFO:     127.0.0.1:48628 - "GET / HTTP/1.1" 200 OK
pdf_bot-1     | 2024-01-04 06:36:21.249 Uncaught app exception
pdf_bot-1     | Traceback (most recent call last):
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
pdf_bot-1     |     exec(code, module.__dict__)
pdf_bot-1     |   File "/app/pdf_bot.py", line 95, in <module>
pdf_bot-1     |     main()
pdf_bot-1     |   File "/app/pdf_bot.py", line 91, in main
pdf_bot-1     |     qa.run(query, callbacks=[stream_handler])
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 507, in run
pdf_bot-1     |     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 312, in __call__
pdf_bot-1     |     raise e
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 306, in __call__
pdf_bot-1     |     self._call(inputs, run_manager=run_manager)
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 144, in _call
pdf_bot-1     |     answer = self.combine_documents_chain.run(
pdf_bot-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 512, in run
pdf_bot-1     |     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 312, in __call__
pdf_bot-1     |     raise e
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 306, in __call__
pdf_bot-1     |     self._call(inputs, run_manager=run_manager)
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 136, in _call
pdf_bot-1     |     output, extra_return_dict = self.combine_docs(
pdf_bot-1     |                                 ^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 244, in combine_docs
pdf_bot-1     |     return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 293, in predict
pdf_bot-1     |     return self(kwargs, callbacks=callbacks)[self.output_key]
pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 312, in __call__
pdf_bot-1     |     raise e
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 306, in __call__
pdf_bot-1     |     self._call(inputs, run_manager=run_manager)
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 103, in _call
pdf_bot-1     |     response = self.generate([inputs], run_manager=run_manager)
pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 115, in generate
pdf_bot-1     |     return self.llm.generate_prompt(
pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 496, in generate_prompt
pdf_bot-1     |     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 383, in generate
pdf_bot-1     |     raise e
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 373, in generate
pdf_bot-1     |     self._generate_with_cache(
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 529, in _generate_with_cache
pdf_bot-1     |     return self._generate(
pdf_bot-1     |            ^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/ollama.py", line 209, in _generate
pdf_bot-1     |     final_chunk = self._chat_stream_with_aggregation(
pdf_bot-1     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/ollama.py", line 168, in _chat_stream_with_aggregation
pdf_bot-1     |     for stream_resp in self._create_chat_stream(messages, stop, **kwargs):
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/ollama.py", line 155, in _create_chat_stream
pdf_bot-1     |     yield from self._create_stream(
pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^^
pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 203, in _create_stream
pdf_bot-1     |     raise ValueError(
pdf_bot-1     | ValueError: Ollama call failed with status code 500. Details: llama runner process has terminated
api-1         | INFO:     127.0.0.1:48632 - "GET / HTTP/1.1" 200 OK
api-1         | INFO:     127.0.0.1:52504 - "GET / HTTP/1.1" 200 OK
api-1         | INFO:     127.0.0.1:52510 - "GET / HTTP/1.1" 200 OK
api-1         | INFO:     127.0.0.1:38514 - "GET / HTTP/1.1" 200 OK
api-1         | INFO:     127.0.0.1:38516 - "GET / HTTP/1.1" 200 OK

**Comment by syedazharmbnr1** [comment]
ValueError: Ollama call failed with status code 500. Details: llama runner process has terminated. 
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,61249]   = ["▁ t", "e r", "i n", "▁ a", "e n...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW) 
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors: mem required  = 3647.98 MiB
..................................................................................................
llama_new_context_with_model: n_ctx      = 3072
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  = 1536.00 MiB, K (f16):  768.00 MiB, V (f16):  768.00 MiB
llama_build_graph: non-view tensors processed: 676/676
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1
ggml_metal_init: picking default device: Apple M1
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/var/folders/md/7f9f14d93_ncd5gq9fwf5cqc0000gn/T/ollama3869230972/llama.cpp/gguf/build/metal/bin/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M1
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  =  5726.63 MB
ggml_metal_init: maxTransferRate               = built-in GPU
llama_new_context_with_model: compute buffer total size = 225.19 MiB
llama_new_context_with_model: max tensor size =   102.54 MiB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3649.52 MiB, ( 3650.20 /  5461.34)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  1536.03 MiB, ( 5186.23 /  5461.34)
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =   222.02 MiB, ( 5408.25 /  5461.34)
ggml_metal_graph_compute: command buffer 0 failed with status 5
GGML_ASSERT: /Users/jmorgan/workspace/ollama/llm/llama.cpp/gguf/ggml-metal.m:2353: false
2024/01/04 12:12:41 llama.go:451: signal: abort trap
2024/01/04 12:12:41 llama.go:459: error starting llama runner: llama runner process has terminated
2024/01/04 12:12:41 llama.go:525: llama runner stopped successfully
[GIN] 2024/01/04 - 12:12:41 | 500 |  6.606875459s |       127.0.0.1 | POST     "/api/chat"

**Comment by jexp** [comment]
Does it work on a 2nd attempt?

Perhaps wortwhile to open this on the https://github.com/ollama/ollama github?

Or @mchiang0610 do you have an idea how to get more info why the llama2 runner terminated here?
