### ISSUE TITLE
Failure during `docker compose up`

### ISSUE THREAD

**Issue by craldaz** [docker/genai-stack#120]
Error seems to be `ERROR Failed to start Neo4j on 0.0.0.0:7474.`

About my system: M1 Pro, Sonoma 14.2.1

```
± |main ✓| → docker compose up
WARN[0000] The "OPENAI_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_PROJECT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_DEFAULT_REGION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_PROJECT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_DEFAULT_REGION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_PROJECT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_DEFAULT_REGION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_PROJECT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LANGCHAIN_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_DEFAULT_REGION" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (0/0)                                                                                                                                               docker:desktop-linux
[+] Running 2/0
 ✔ Container genai-stack-database-1    Created                                                                                                                                        0.0s
 ✔ Container genai-stack-pull-model-1  Created                                                                                                                                        0.0s
Attaching to genai-stack-api-1, genai-stack-bot-1, genai-stack-database-1, genai-stack-front-end-1, genai-stack-loader-1, genai-stack-pdf_bot-1, genai-stack-pull-model-1
genai-stack-pull-model-1  | pulling ollama model llama2 using http://host.docker.internal:11434
genai-stack-database-1    | Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
genai-stack-database-1    | Applying default values for plugin apoc to neo4j.conf
genai-stack-database-1    | Skipping dbms.security.procedures.unrestricted for plugin apoc because it is already set.
genai-stack-database-1    | You may need to add apoc.* to the dbms.security.procedures.unrestricted setting in your configuration file.
pulling manifest
pulling manifest
pulling manifest
pulling manifest
genai-stack-pull-model-1  | pulling 8934d96d3f08... 100% ▕▏ 3.8 GB
genai-stack-pull-model-1  | pulling 8c17c2ebb0ea... 100% ▕▏ 7.0 KB
genai-stack-pull-model-1  | pulling 7c23fb36d801... 100% ▕▏ 4.8 KB
genai-stack-pull-model-1  | pulling 2e0493f67d0c... 100% ▕▏   59 B
genai-stack-pull-model-1  | pulling fa304d675061... 100% ▕▏   91 B
genai-stack-pull-model-1  | pulling 42ba7f8a01dd... 100% ▕▏  557 B
genai-stack-pull-model-1  | verifying sha256 digest
genai-stack-pull-model-1  | writing manifest
genai-stack-pull-model-1  | removing any unused layers
genai-stack-pull-model-1  | success
genai-stack-database-1    | 2024-01-22 05:12:37.453+0000 INFO  ======== Neo4j 5.11.0 ========
genai-stack-pull-model-1 exited with code 0
genai-stack-database-1    | 2024-01-22 05:12:45.613+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
genai-stack-database-1    | java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
genai-stack-database-1    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:272) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:208) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:38) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:187) [neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:30) [neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@4b0bd001' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to read log version and last committed tx from '/data/transactions/system/neostore.transaction.db.0'. Was only able to read 0 bytes, but was expecting 8".
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:365) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	... 5 more
genai-stack-database-1    | Caused by: org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.
genai-stack-database-1    | 	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.assertDatabaseAvailable(DatabaseAvailabilityGuard.java:154) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginKernelTransaction(GraphDatabaseFacade.java:148) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:117) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:89) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:113) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:107) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:102) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTx(GraphDatabaseTransactions.java:93) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.SystemGraphComponents.initializeSystemGraph(SystemGraphComponents.java:83) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.DefaultSystemGraphInitializer.initializeSystemGraph(DefaultSystemGraphInitializer.java:38) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.SystemGraphInitializer.start(SystemGraphInitializer.java:27) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:348) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	... 5 more
genai-stack-database-1    | Caused by: java.lang.RuntimeException: org.neo4j.kernel.impl.transaction.log.entry.IncompleteLogHeaderException: Unable to read log version and last committed tx from '/data/transactions/system/neostore.transaction.db.0'. Was only able to read 0 bytes, but was expecting 8
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.findLogTail(DetachedLogTailScanner.java:138) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.getTailMetadata(DetachedLogTailScanner.java:394) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.CheckpointLogFile.getTailMetadata(CheckpointLogFile.java:240) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFiles.getTailMetadata(TransactionLogFiles.java:92) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.database.Database.getLogTail(Database.java:648) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.database.Database.specificStart(Database.java:416) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.database.AbstractDatabase.start(AbstractDatabase.java:160) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.DatabaseLifecycles.startDatabase(DatabaseLifecycles.java:123) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.DatabaseLifecycles$SystemDatabaseStarter.start(DatabaseLifecycles.java:146) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:348) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	... 5 more
genai-stack-database-1    | Caused by: org.neo4j.kernel.impl.transaction.log.entry.IncompleteLogHeaderException: Unable to read log version and last committed tx from '/data/transactions/system/neostore.transaction.db.0'. Was only able to read 0 bytes, but was expecting 8
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.entry.LogFormat.checkUnderflow(LogFormat.java:276) ~[neo4j-wal-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.entry.LogFormat.parseHeader(LogFormat.java:188) ~[neo4j-wal-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.entry.LogHeaderReader.readLogHeader(LogHeaderReader.java:90) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.entry.LogHeaderReader.readLogHeader(LogHeaderReader.java:75) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.entry.LogHeaderReader.readLogHeader(LogHeaderReader.java:49) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFile.extractHeader(TransactionLogFile.java:696) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFile.extractHeader(TransactionLogFile.java:340) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.getFirstTransactionId(DetachedLogTailScanner.java:184) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.noCheckpointLogTail(DetachedLogTailScanner.java:172) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.findLogTail(DetachedLogTailScanner.java:109) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.getTailMetadata(DetachedLogTailScanner.java:394) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.checkpoint.CheckpointLogFile.getTailMetadata(CheckpointLogFile.java:240) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFiles.getTailMetadata(TransactionLogFiles.java:92) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.database.Database.getLogTail(Database.java:648) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.database.Database.specificStart(Database.java:416) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.database.AbstractDatabase.start(AbstractDatabase.java:160) ~[neo4j-kernel-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.DatabaseLifecycles.startDatabase(DatabaseLifecycles.java:123) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.dbms.database.DatabaseLifecycles$SystemDatabaseStarter.start(DatabaseLifecycles.java:146) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:348) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.11.0.jar:5.11.0]
genai-stack-database-1    | 	... 5 more
genai-stack-database-1    | 2024-01-22 05:12:45.618+0000 INFO  Neo4j Server shutdown initiated by request
genai-stack-database-1    | 2024-01-22 05:12:45.619+0000 INFO  Stopped.
genai-stack-database-1 exited with code 1
dependency failed to start: container genai-stack-database-1 exited (1)
```

**Comment by sidagarwal04** [comment]
This seems like a similar issue which I faced earlier. Try the solution provided in this issue: https://github.com/docker/genai-stack/issues/109

Make sure to use following command to rebuild the script: `docker compose up --build`

**Comment by jexp** [comment]
Thanks @sidagarwal04 
@craldaz did that help you? Otherwise you can also try to delete the `data` folder that's crated by the container before running `docker compose up`
