### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by karthik-mukund** [docker/genai-stack#42]
I get the following error after starting the application and typing any query

ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f1a50107ed0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))

**Comment by tomasonjo** [comment]
Which OS do you have? Seems like the LLM is not running, take a look at this section in the README:

```
MacOS Install [Ollama](https://ollama.ai/) in MacOS and start it before running docker compose up.

Linux No need to install Ollama manually, it will run in a container as part of the stack when running with the Linux profile: run docker compose up --profile linux.

Windows Not supported by Ollama, so Windows users need to generate a OpenAI API key and configure the stack to use gpt-3.5 or gpt-4 in the .env file.
```

**Comment by karthik-mukund** [comment]
CentOS 8.0 is the OS. The following is a slightly more detailed info

git-pdf_bot-1     | 2023-10-11 18:38:23.826 Embedding: Using SentenceTransformer
git-pdf_bot-1     | 2023-10-11 18:38:23.827 LLM: Using Ollama: llama2
git-pdf_bot-1     | 2023-10-11 18:38:34.191 Embedding: Using SentenceTransformer
git-pdf_bot-1     | 2023-10-11 18:38:34.192 LLM: Using Ollama: llama2
git-pdf_bot-1     | 2023-10-11 18:38:59.267 Embedding: Using SentenceTransformer
git-pdf_bot-1     | 2023-10-11 18:38:59.267 LLM: Using Ollama: llama2
git-pdf_bot-1     | 2023-10-11 18:39:07.797 Uncaught app exception
git-pdf_bot-1     | Traceback (most recent call last):
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
git-pdf_bot-1     |     sock = connection.create_connection(
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
git-pdf_bot-1     |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
git-pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
git-pdf_bot-1     |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
git-pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
git-pdf_bot-1     |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
git-pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     | socket.gaierror: [Errno -2] Name or service not known
git-pdf_bot-1     | 
git-pdf_bot-1     | The above exception was the direct cause of the following exception:
git-pdf_bot-1     | 
git-pdf_bot-1     | Traceback (most recent call last):
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
git-pdf_bot-1     |     response = self._make_request(
git-pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
git-pdf_bot-1     |     conn.request(
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
git-pdf_bot-1     |     self.endheaders()
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
git-pdf_bot-1     |     self._send_output(message_body, encode_chunked=encode_chunked)
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
git-pdf_bot-1     |     self.send(msg)
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/http/client.py", line 979, in send
git-pdf_bot-1     |     self.connect()
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
git-pdf_bot-1     |     self.sock = self._new_conn()
git-pdf_bot-1     |                 ^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 210, in _new_conn
git-pdf_bot-1     |     raise NameResolutionError(self.host, self, e) from e
git-pdf_bot-1     | urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7f1a50107ed0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)
git-pdf_bot-1     | 
git-pdf_bot-1     | The above exception was the direct cause of the following exception:
git-pdf_bot-1     | 
git-pdf_bot-1     | Traceback (most recent call last):
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
git-pdf_bot-1     |     resp = conn.urlopen(
git-pdf_bot-1     |            ^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
git-pdf_bot-1     |     retries = retries.increment(
git-pdf_bot-1     |               ^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
git-pdf_bot-1     |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
git-pdf_bot-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f1a50107ed0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))
git-pdf_bot-1     | 
git-pdf_bot-1     | During handling of the above exception, another exception occurred:
git-pdf_bot-1     | 
git-pdf_bot-1     | Traceback (most recent call last):
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
git-pdf_bot-1     |     exec(code, module.__dict__)
git-pdf_bot-1     |   File "/app/pdf_bot.py", line 95, in <module>
git-pdf_bot-1     |     main()
git-pdf_bot-1     |   File "/app/pdf_bot.py", line 91, in main
git-pdf_bot-1     |     qa.run(query, callbacks=[stream_handler])
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 501, in run
git-pdf_bot-1     |     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 306, in __call__
git-pdf_bot-1     |     raise e
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 300, in __call__
git-pdf_bot-1     |     self._call(inputs, run_manager=run_manager)
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 139, in _call
git-pdf_bot-1     |     answer = self.combine_documents_chain.run(
git-pdf_bot-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 506, in run
git-pdf_bot-1     |     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 306, in __call__
git-pdf_bot-1     |     raise e
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 300, in __call__
git-pdf_bot-1     |     self._call(inputs, run_manager=run_manager)
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 119, in _call
git-pdf_bot-1     |     output, extra_return_dict = self.combine_docs(
git-pdf_bot-1     |                                 ^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 171, in combine_docs
git-pdf_bot-1     |     return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 257, in predict
git-pdf_bot-1     |     return self(kwargs, callbacks=callbacks)[self.output_key]
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 306, in __call__
git-pdf_bot-1     |     raise e
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 300, in __call__
git-pdf_bot-1     |     self._call(inputs, run_manager=run_manager)
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 93, in _call
git-pdf_bot-1     |     response = self.generate([inputs], run_manager=run_manager)
git-pdf_bot-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 103, in generate
git-pdf_bot-1     |     return self.llm.generate_prompt(
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 469, in generate_prompt
git-pdf_bot-1     |     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 359, in generate
git-pdf_bot-1     |     raise e
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 349, in generate
git-pdf_bot-1     |     self._generate_with_cache(
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 501, in _generate_with_cache
git-pdf_bot-1     |     return self._generate(
git-pdf_bot-1     |            ^^^^^^^^^^^^^^^
git-pdf_bot-1     |   File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/ollama.py", line 98, in _generate
git-pdf_bot-1     |     final_chunk = super()._stream_with_aggregation(

**Comment by tomasonjo** [comment]
does the LLM docker run? Are you using `run docker compose up --profile linux`.
If the LLM docker container is up and running try the following env variable:

```
OLLAMA_BASE_URL=http://llm:11434
```

**Comment by karthik-mukund** [comment]
I used `docker compose --profile linux up` but still running into the following issue

```
git-pull-model-1  | pulling ollama model llama2 using http://host.docker.internal:11434
git-pull-model-1  | Error: Head "http://host.docker.internal:11434/": dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host
git-pull-model-1 exited with code 1
```

**Comment by Syulin7** [comment]
@karthik-mukund  this issue https://github.com/docker/genai-stack/issues/39 can resolve the problem.

**Comment by jexp** [comment]
Super, seems there is a solution.
